recorder: AudRecorder.sv tb_audrecorder.sv
	vcs tb_audrecorder.sv AudRecorder.sv -full64 -R -debug_access+all +v2k -sverilog
i2c: I2C_working.sv tb_i2c.sv
	vcs tb_i2c.sv I2C_working.sv -full64 -R -debug_access+all +v2k -sverilog
myi2c: I2C.sv tb_i2c.sv
	vcs tb_i2c.sv I2C.sv -full64 -R -debug_access+all +v2k -sverilog